apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/manuelnucci/argocd-demo.git
    targetRevision: main
    path: overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
