namePrefix: production-
namespace: production
commonLabels:
  variant: production
commonAnnotations:
  note: Hello, I am production!
resources:
  - ../../base
images:
  - name: manuelnucci/argocd-app
    newTag: "1.0"
